# Generated by Django 2.1.2 on 2018-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('introduction', models.TextField()),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
