# Generated by Django 2.1.2 on 2019-05-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
    ]
